CREATE DATABASE IF NOT EXISTS solicitacao_compras;
USE solicitacao_compras;

CREATE TABLE USUARIOS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  SENHA VARCHAR(100) NOT NULL,
  DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PRODUTOS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(100) NOT NULL,
  DESCRICAO TEXT,
  PRECO DECIMAL(10,2) NOT NULL,
  ESTOQUE INT NOT NULL,
  DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SOLICITACAO_COMPRAS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_USUARIO INT NOT NULL
);

CREATE TABLE ITENS_SOLICITACAO (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  ID_SOLICITACAO INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
  QUANTIDADE INT NOT NULL,
  PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
  FOREIGN KEY (ID_SOLICITACAO) REFERENCES SOLICITACAO_COMPRAS(ID)
);
